# Generated by Django 4.2.1 on 2023-05-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='vars_category',
            new_name='variation_category',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='vars_value',
            new_name='variation_value',
        ),
    ]
